### ISSUE TITLE
Not for beginners

### ISSUE THREAD

**Issue by JMLT85** [Jorricks/unrar-angel#2]
Hi,
I am not very good with Ubuntu but had lots of issues while trying to install it. Instructions probably for very advanced users only, not some beginners like me. Installation instructions given .. but then at the bottom commands as well, which doesn't say after when to use them. Had lots of issues and missing packages to install ... (kimsufi server with Ubuntu 16.04) found many on google and made them working. but biggest issue is the RARLAB ... spend hours and hours trying it to work ... but allways same issue ....

sudo /usr/bin/python3.5 /home/desktop/unrar-angel/angel.py param
Traceback (most recent call last):
  File "/home/desktop/unrar-angel/angel.py", line 8, in <module>
    from watcher import Watcher
  File "/home/desktop/unrar-angel/watcher.py", line 5, in <module>
    from unrarrer import UnRAR
  File "/home/desktop/unrar-angel/unrarrer.py", line 5, in <module>
    from unrar import rarfile
  File "/usr/local/lib/python3.5/dist-packages/unrar/rarfile.py", line 26, in <module>
    from unrar import unrarlib
  File "/usr/local/lib/python3.5/dist-packages/unrar/unrarlib.py", line 57, in <module>
    raise LookupError("Couldn't find path to unrar library.")
LookupError: Couldn't find path to unrar library.

locating library .. 
locate libunrar.so
/usr/local/bin/libunrar.so (FOUND)
sh-4.3$ locate libunrar.a (not found)

so compilation did not work ...

compiling again ... and checkinstall again
Done. The new package has been installed and saved to
 /usr/local/bin/unrar/unrar_20190208-1_amd64.deb

lets try again 

sudo /usr/bin/python3.5 /home/desktop/unrar-angel/angel.py param
Traceback (most recent call last):
  File "/home/desktop/unrar-angel/angel.py", line 8, in <module>
    from watcher import Watcher
  File "/home/desktop/unrar-angel/watcher.py", line 5, in <module>
    from unrarrer import UnRAR
  File "/home/desktop/unrar-angel/unrarrer.py", line 5, in <module>
    from unrar import rarfile
  File "/usr/local/lib/python3.5/dist-packages/unrar/rarfile.py", line 26, in <module>
    from unrar import unrarlib
  File "/usr/local/lib/python3.5/dist-packages/unrar/unrarlib.py", line 57, in <module>
    raise LookupError("Couldn't find path to unrar library.")
LookupError: Couldn't find path to unrar library.

I guess I will have to do unrar manually as it not up to my knowledge how to install and make it work .. sad but true .... i give up

**Comment by Jorricks** [comment]
Hello JMLT85,

That unfortunate! 
I have to give it to you, I hate going through the installation process of the unrar module as well. For me it wasn't an easy task neither.
I'll try to see if I can provide you some tips soon.

**Comment by Jorricks** [comment]
So the original documentation of the rar module can be found here: https://pypi.org/project/unrar/.
Although it's an awesome rar module, their documentation never worked for me regarding the installation issue you have as well. 
Could you try out this installation instruction :
https://github.com/matiasb/python-unrar/blob/master/README.md
Seems to be the latest and (easiest) out there.

Please let me know if this worked for you.
